/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
/**
 *
 * @author chris
 */
public class OpenGame extends javax.swing.JPanel
{   
    private Menu m;
    private int igid;
    private String hostName;
    public OpenGame(String gid,String hostName ,Menu m)
    {
        initComponents();
        this.gid.setText(gid);
        this.uid.setText(hostName);
        
        this.hostName = hostName;
        this.igid = Integer.parseInt(gid);
        this.m = m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        gid = new javax.swing.JLabel();
        uid = new javax.swing.JLabel();
        joinButton = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        gid.setText("Game ID");
        jPanel1.add(gid);

        uid.setText("User ID");
        jPanel1.add(uid);

        joinButton.setText("Join");
        joinButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                joinButtonActionPerformed(evt);
            }
        });
        jPanel1.add(joinButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void joinButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_joinButtonActionPerformed
    {//GEN-HEADEREND:event_joinButtonActionPerformed
        m.joinGame(igid,this,hostName);
    }//GEN-LAST:event_joinButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gid;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton joinButton;
    private javax.swing.JLabel uid;
    // End of variables declaration//GEN-END:variables
}
